import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Barlow_Condensed } from "next/font/google";
import Wrapper from "@/components/shared/Wrapper";
import ResponsiveNavbar from "@/components/widgets/Navbar/ResponsiveNavbar";

const barlowCondensed = Barlow_Condensed({
  subsets: ["latin"],
  weight: ["100", "300","400", "500","600", "700", "800", "900"],
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Burger Shop | Healthy Food",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${barlowCondensed.className} ${geistMono.variable} antialiased`}
      >
        <Wrapper>
          <ResponsiveNavbar />
          {children}
        </Wrapper>
      </body>
    </html>
  );
}
